### ISSUE TITLE
Popup does not show on first click

### ISSUE THREAD

**Issue by mjut** [mjut/trailmap#1]
When clicking on a track the popup does not show on the first click.
It needs at least two clicks. 

I do not know how to fix that.

**Comment by ibrierley** [comment]
If you have a live example up somewhere, I don't mind taking a quick peek when I get chance.

**Comment by mjut** [comment]
That's nice!
You can see the example over here: https://mjut.github.io/trailmap/trailmap.html
Everything works as expected, but the first click is not being recognized.

I did change your code: I wanted an popup instead of the alert.
See:
https://github.com/mjut/trailmap/blob/ee3e7bdabd365fcd6ed02a19ed54863a8e681af8/trailmap.html#L111

**Comment by ibrierley** [comment]
You want to add the gpx.bindPopup stuff to the .on('loaded', ...... section, rather than the .on('click', ... section basically.

Currently, logically, you are saying "On click, add a popup when it's clicked". When it should be "On loaded, add a popup when it's clicked". So just move that code to the other section.

**Comment by mjut** [comment]
Ha,
Ian, thanks a ton!
Makes totally sense. Thanks for your help on my way to manage Javascript ;)
Cheers!
Stephan
